---
title: "EDA"
author: "Phoebe Abramowitz and Jack Moorer"
date: "4/12/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Cleaning

```{r clean data}
#load packages
library(dplyr)
library(astsa)

#read in data
raw_birthrates = read.csv("../data/daily-total-female-births-in-cal.csv")

#remove final row
clean_birthrates <- filter(raw_birthrates, Date!="Daily total female births in California")

#define column names
colnames(clean_birthrates) <-  c('date',"daily_female_births")

#convert dates to Data data type
clean_birthrates$date <- as.Date(clean_birthrates$date)

#make dates row names
birthrates <- clean_birthrates$daily_female_births
female_birthrates <- data.frame(birthrates)
rownames(female_birthrates) <- clean_birthrates$date

#examine data
head(female_birthrates)
```

#EDA
```{r}
#plot time series
plot.ts(female_birthrates, main = "Time Series Plot of Female Birthrate Data")
```

Let's see if there is an underlying trend in our data by fitting a linear model.

```{r}
#regress birthrates on time
x <- 1:nrow(female_birthrates)
reg <- lm(birthrates ~ x)

#plot ts with regression model
plot.ts(female_birthrates)
abline(a = reg$coefficients[[1]], b = reg$coefficients[[2]], col = 'red')
```
 
It seems like there is a slight trend. Let's plot the residuals of the regression, which should be the detrended time series.


```{r}
#plot detrended time series vie OLS regression
plot(resid(reg), type = 'l', main = "Detrended via Simple OLS", ylab = "Birthrates Detrended", xlab = "Time")
```
 
```{r}
#acf of time series detrended via OLS
acf(reg$residuals, main = "ACF of Birthrates Detrended via OLS")
```
 

Let's look at the first difference.
 
 
```{r}
#take the first difference of the time series
diff_vals <- diff(birthrates)

#create differnce dataframe
first_diff <- data.frame(diff_vals)
plot.ts(first_diff, main = "First Difference of Birthrates Time Series")
```
 
```{r}
#plot acf of first diffence
acf(first_diff, main = "ACF of First Difference of Birthrates")
```
 
Let's look at the second difference.

```{r}
second_diff_vals <- diff(diff(birthrates))

#create differnce dataframe
second_diff <- data.frame(second_diff_vals)
plot.ts(second_diff, main = "First Difference of Birthrates Time Series")
```
```{r}
#acf of second diff
acf(second_diff, main = "ACF of Second Difference of Birthrates")
```
